name = "dogonomicon-worker"
main = "src/index.ts"
compatibility_date = "2022-06-13"

# This is my account id
account_id = "ddbaca336ddafda25acaf07053ea18d1"
workers_dev = true

[[r2_buckets]]
binding = 'R2_BUCKET'
bucket_name= 'dev-jakeprem-dogonomicon'
