defmodule DogBreedsWeb.Layouts do
  @moduledoc """
  Generated by Phoenix
  https://hexdocs.pm/phoenix/Phoenix.Controller.html#module-rendering-and-layouts
  """

  use DogBreedsWeb, :html

  embed_templates "layouts/*"
end
